### PR TITLE
fix: Overlapping components near searchbar

### LINKED ISSUE #100: Overlapping components near the searchbar
image
The searchbar and the country suggestion texts are kinda overlapping. UI components not rendered properly.

### PR DESCRIPTION
**Pull request by ansisme**
fixes #100
- resolved overlapping searchbar and country suggestions components
- adjusted background color to fill entire viewport

### CODE REVIEW

**Comment by HridoyHazard** [comment]
can you remove the env file plz

**Comment by ansisme** [comment]
sure, but env file was a part of your main branch too.
so shall i simply delete the env file ?

**Comment by HridoyHazard** [comment]
solve the conflicts plz

**Comment by ansisme** [comment]
done

**Review by HridoyHazard — APPROVED** [review]

**Pull request merged**
