### PR TITLE
Marathi Language Added

### PR DESCRIPTION
**Pull request by nileshlad09**
image

hi @HridoyHazard , I added one more language

### CODE REVIEW

**Comment by HridoyHazard** [comment]
check failed! can you plz check where did you make mistake

**Comment by nileshlad09** [comment]
how can i find that ?

**Comment by nileshlad09** [comment]
ok let me check ones

**Comment by nileshlad09** [comment]
@HridoyHazard you can check now

**Comment by HridoyHazard** [comment]
so many branch conflicts 
can u plz fix it ?

**Comment by nileshlad09** [comment]
@HridoyHazard  you can check now ?

**Comment by HridoyHazard** [comment]
hi can you plz make another fresh pr. this pr seems very messed up. i'm closing it. make another fresh pr and i'm merging it.

**Pull request closed without merging**
