### PR TITLE
adding slide in animation to the logo

### PR DESCRIPTION
**Pull request by kasuba97**
this is my first hackthober first pull request am excited.

### CODE REVIEW

**Comment by HridoyHazard** [comment]
your code is not compiling. fix what's missing

**Comment by kasuba97** [comment]
you need to run `npm i` to install the new gsap Independence

**Comment by kasuba97** [comment]
forgot to install gsap during `//installation `cleanup

**Comment by HridoyHazard** [comment]
who me a video what did you added. because it not deploying

**Comment by kasuba97** [comment]
https://user-images.githubusercontent.com/90401451/197340248-f8d1888b-c068-4f94-b175-bf071e4fb410.mp4

need to work on the flickering though

**Pull request merged**
