### PR TITLE
Fixed typo in DetailsCard

### PR DESCRIPTION
**Pull request by KKlob**
Changed "RealFell" to "RealFeel" and adjusted some spacing

### CODE REVIEW

**Comment by HridoyHazard** [comment]
searching is not working. can you plz check again

**Comment by KKlob** [comment]
Looks like the deploy preview doesn't have an API key to use. The preview has REACT_APP_API_KEY resolve to undefined. Trying to replicate locally with my dev branch but my search works fine.

**Comment by KKlob** [comment]
After combing through the recent closed pull request, it looks like PR #19 caused an issue with the API key.

**Comment by KKlob** [comment]
Combed through the recent commits, seems PR #11 removed the .env file that defined REACT_APP_API_KEY. This is why the search stopped working

**Comment by KKlob** [comment]
please add hacktoberfest-accepted tag to this PR

**Pull request merged**
