### PR TITLE
fix #73

### PR DESCRIPTION
**Pull request by devilkiller-ag**
Fixed dark mode sub-heading color.

### CODE REVIEW

**Comment by HridoyHazard** [comment]
it's not changing theme. i guess there are bug in your code. fix it plz

**Comment by devilkiller-ag** [comment]
Sure I will do it as soon as possible

**Comment by HridoyHazard** [comment]
did you fixed it?

**Comment by devilkiller-ag** [comment]
@HridoyHazard I am sorry I was busy for 2 days, I will complete it tomorrow. Sorry for the inconveniences.

**Comment by HridoyHazard** [comment]
after fixing make a comment plz

**Comment by devilkiller-ag** [comment]
@HridoyHazard  Please check the changes

**Comment by HridoyHazard** [comment]
can you show me a video or gif ? because in deployed version it not working

**Comment by devilkiller-ag** [comment]
Screenshot (56)

**Comment by devilkiller-ag** [comment]
image

**Comment by devilkiller-ag** [comment]
image

**Comment by HridoyHazard** [comment]
> image

why did you delete the heard? you could just mention me...i was busy and didn't see this pr

**Pull request closed without merging**
